# Generated by Django 3.1.1 on 2020-09-25 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exams',
            name='sub_category',
        ),
        migrations.AddField(
            model_name='subcategory',
            name='sub_category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='subcategories', to='exams.exams'),
            preserve_default=False,
        ),
    ]
